apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-azurefile-pvc
spec:
  accessModes:
    - ReadWriteMany # coz it can be read/written from many pods at once
  storageClassName: my-azurefile-sc # ref to 01
  resources:
    requests:
      storage: 5Gi